name: End-to-end tests
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install      
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Archive Failure Screenshots 
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Screenshots
          path: cypress/screenshots/todo.cy.js/*
      - name: Archive Video 
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Video
          path: cypress/videos/*
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 
            cypress/reports/mocha/*.json
 
    

    
      


      

          
